pipeline:
  name: lambda-runtime
  identifier: lambdaruntime
  stages:
    - stage:
        name: Clone Stage
        identifier: clone_stage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: GitClone
                  name: Clone Private Repo
                  identifier: clone_private_repo
                  spec:
                    connectorRef: connect_to_techwhisperin
                    repoName: <+input>
                    build: <+input>
              - step:
                  type: Run
                  identifier: clone_repo
                  name: Clone Repo
                  spec:
                    shell: Sh
                    command: |
                      git clone https://<+secrets.getValue("GITHUB_TOKEN")>@github.com/techwhisper-in/<+execution.steps.clone_private_repo.spec.execution.steps.clone_private_repo.spec.repoName>
  projectIdentifier: myfirstproject
  orgIdentifier: default
