pipeline:
  name: lambda-runtime
  identifier: lambdaruntime
  projectIdentifier: myfirstproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Repo Clone
        identifier: repo_clone
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: GitClone
                  name: Clone Private Repo
                  identifier: clone_private_repo
                  spec:
                    connectorRef: connect_to_techwhisperin
                    repoName: <+input>
                    build: <+input>
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: repo_name= <+execution.steps.clone_private_repo.spec.repoName> echo $repo_name cd $repo_name python3 change-runtime.py "hello" cd .. rm -rf "$repo_name"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
