pipeline:
  name: lambda-runtime
  identifier: lambdaruntime
  projectIdentifier: myfirstproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Repo Clone
        identifier: repo_clone
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: GitClone
                  name: Clone Private Repo
                  identifier: clone_private_repo
                  spec:
                    connectorRef: connect_to_techwhisperin
                    repoName: <+input>
                    build: <+input>
                  timeout: 10m
        tags: {}
