pipeline:
  name: lambda-runtime
  identifier: lambdaruntime
  projectIdentifier: myfirstproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Repo Clone
        identifier: repo_clone
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          github_connector=<+execution.steps.ShellScript_1.spec.environmentVariables.github_connector>
                          echo $github_connector
                          echo "https://<+secrets.getValue("connect_to_techwhisperin")>@github.com/$account_name/$repo_name.git"
                          account_name=<+execution.steps.ShellScript_1.spec.environmentVariables.account_name>
                          repo_name=<+execution.steps.ShellScript_1.spec.environmentVariables.repo_name>
                          echo $repo_name
                          echo "https://github.com/$account_name/$repo_name.git"
                          git clone "https://<+secrets.getValue("connect_to_techwhisperin")>@github.com/$account_name/$repo_name.git"
                          cd $repo_name
                          python3 change-runtime.py "hello"
                          echo "ankit"
                          cd ..
                          rm -rf "$repo_name"
                    environmentVariables:
                      - name: github_connector
                        type: String
                        value: <+input>
                      - name: account_name
                        type: String
                        value: <+input>
                      - name: repo_name
                        type: String
                        value: <+input>
                    outputVariables: []
                  timeout: 10m
        tags: {}
