pipeline:
  name: lambda-runtime
  identifier: lambdaruntime
  projectIdentifier: myfirstproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Plan
        identifier: plan
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        connectorRef: connect_to_techwhisperin
                        type: Github
                        script: |
                          repo_name=<+execution.steps.ShellScript_1.spec.environmentVariables.repo_name>
                          echo $repo_name
                          git clone "https://github.com/techwhisper-in/$repo_name.git"
                          cd $repo_name
                          python3 change-runtime.py "hello"
                          echo "ankit"
                          cd ..
                          rm -rf "$repo_name"
                    environmentVariables:
                      - name: repo_name
                        type: String
                        value: <+input>
                    outputVariables: []
                  timeout: 10m
        tags: {}
