pipeline:
  name: lambda-runtime
  identifier: lambdaruntime
  projectIdentifier: myfirstproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Repo Clone
        identifier: repo_clone
        description: ""
        type: Custom
        variables:
          - name: github_connect_secret
            type: Secret
            required: true
            value: <+input>
          - name: account_name
            type: String
            required: true
            value: <+input>
          - name: repo_name
            type: String
            required: true
            value: <+input>
          - name: Region
            type: String
            required: true
            value: <+input>.default(us-east-1).allowedValues(us-east-1,us-east-2)
          - name: Lambda_Functions
            type: String
            required: true
            description: Write "All" if action to be performed on all the lambda-functions
            value: <+input>.default(All)
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          pwd
                          export PYTHONUNBUFFERED=1
                          account_name=<+stage.variables.account_name>
                          repo_name=<+stage.variables.repo_name>
                          echo $repo_name
                          echo "https://github.com/$account_name/$repo_name.git"
                          echo <+stage.variables.Region>
                          echo <+stage.variables.Lambda_Functions>
                          git clone "https://<+stage.variables.github_connect_secret>@github.com/$account_name/$repo_name.git"
                          cd $repo_name
                          python3 change-runtime.py "hello"
                          echo "ankit"
                          cd ..
                          rm -rf "$repo_name"
                          echo <+stage.variables.Lambda_Functions>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_2
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: pwd
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
