pipeline:
  name: Clone Private GitHub Repo
  identifier: clone_private_github_repo
  stages:
    - stage:
        name: Clone Stage
        identifier: clone_stage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: connect_to_techwhisperin
                    repoName: <+input>
                    build: <+input>
              - step:
                  type: Run
                  identifier: clone_repo
                  name: Clone Repo
                  spec:
                    shell: Sh
                    command: |
                      git clone https://<+secrets.getValue("GITHUB_TOKEN")>@github.com/techwhisper-in/<+pipeline.stages.clone_stage.spec.execution.steps.GitClone_1.spec.repoName>.git
  projectIdentifier: myfirstproject
  orgIdentifier: default
