pipeline:
  name: Clone-Private-GitHub-Repo
  identifier: clone_private_github_repo
  projectIdentifier: myfirstproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: clone_repo
        identifier: clone_repo
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: connect_to_techwhisperin
                    repoName: lambda-runtime
                    build:
                      type: branch
                      spec:
                        branch: main
          caching:
            enabled: false
            paths: []
