pipeline:
  name: Clone-Private-GitHub-Repo
  identifier: clone_private_github_repo
  projectIdentifier: myfirstproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: clone_repo
        identifier: clone_repo
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: pwd
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Bash
                    command: |-
                      pwd
                      ls
          caching:
            enabled: false
            paths: []
        delegateSelectors:
          - linux-amd64
          - docker-delegate
